@WebApi_HostAddress = https://localhost:5001

GET {{WebApi_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Il9HLS03T192Y3djRjAzeXIyTWtQYyJ9.eyJuaWNrbmFtZSI6ImRldiIsIm5hbWUiOiJkZXZAdGVzdC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zLmdyYXZhdGFyLmNvbS9hdmF0YXIvZWI1MWU4MDAxZWJjZTJlMjUxYTkxN2I5MGU0MTM2NTE_cz00ODAmcj1wZyZkPWh0dHBzJTNBJTJGJTJGY2RuLmF1dGgwLmNvbSUyRmF2YXRhcnMlMkZkZS5wbmciLCJ1cGRhdGVkX2F0IjoiMjAyMy0xMi0zMVQwNjo1Njo0NC44MTVaIiwiaXNzIjoiaHR0cHM6Ly9kZXYtZWtydzFsZnIudXMuYXV0aDAuY29tLyIsImF1ZCI6ImhnZW50ZWltandWYU5pYkY4N1F6YUUzMU04QTJjWkluIiwiaWF0IjoxNzA0MDA3NjUxLCJleHAiOjE3MDQwNDM2NTEsInN1YiI6ImF1dGgwfDY1OGYwNDkyYWExMzIzYTk3NDE4MzNkZCJ9.OjQQBqd_isV7yZn_g46jhJFMdXEsN_aPKYBlsoTfG7k
###

GET {{WebApi_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiaXNzIjoiaHR0cHM6Ly9kZXYtZWtydzFsZnIudXMuYXV0aDAuY29tLyJ9..pH00Lu8ycC5OnpJ7.I5a_M8viy8K1D7mkGUn0jOedo2QaNYdmzeXCv62ZDJ5DJJ-LsTCeRscR2nYfm4B2sm432-30BtHTOh3vmt5QppJT5KazVCoHDY-qOdcE6iWnJcC6WAomJTI6UfL2mXfqnVsvZ6OjPxp-TVg61OgbrTFCwO3hRFr8Ewn2Q2FOvsCAKJfukzIKyfGKJ4iD0EKItB06wbr4mgKQhaF_9a4aogvUYxSpwWpmGwpV7hY8W3-kilP3LLD4mg1CDRbbIiNYHlesQxxafzj5wcjCKd4Yt5qfh3PsVHAwfzT8BecX9k-e-vxRQfvRkFXWE92KIZOPsyd8PunJnUzqM3w.0UhpVZZHAuHkWbLXBc7fgw
###
